### ISSUE TITLE
don't trigger tests on removed branches

### ISSUE THREAD

**Issue by xmonader** [AhmedHanafy725/0-CI#19]
looks like zeroci listen to the changes on all of the branches even if the even was "branch removed". Clearly that's not the intention.

**Comment by AhmedHanafy725** [comment]
If the branch is deleted, it won't trigger the tests, but I think this only happens if someone push then the branch is deleted, as cloning the branch is not done once a commit is pushed, so it takes sometime (also depending on the workers if they are busy), and the farther solution of this issue #16 will decrease the occurrence of that issue.
